name:               "Micker Rsync Deploy"
author:             Micker
description:        "Rsync Deploy"
branding:
  icon:             arrow-left
  color:            blue
inputs:
  DEPLOY_KEY:
    description:    "Deploy key"
    required:       true
  ARGS:
    description:    "Args"
    required:       true
  FOLDER:
    description:    "Client Folder"
    required:       true
  SERVER_IP:
    description:    "Server IP"
    required:       true
  USERNAME:
    description:    "Host Name"
    required:       true
  SERVER_DESTINATION:
    description:    "Serevr file location"
    required:       true
  PROJECT_NAME:
    description:    "Project Name"
    required:       true

runs:
  using:            'docker'
  image:            'Dockerfile'
  args:
    - ${{ inputs.DEPLOY_KEY }}
    - ${{ inputs.ARGS }}
    - ${{ inputs.FOLDER }}
    - ${{ inputs.SERVER_IP }}
    - ${{ inputs.USERNAME }}
    - ${{ inputs.SERVER_DESTINATION }}
    - ${{ inputs.PROJECT_NAME}}
