# This is a basic workflow to help you get started with Actions

name: IdentityServer Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    #inputs:
        #name:
          #description: 'Person to greet'
          #required: true
          #default: 'Mona the Octocat'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          token: ${{secrets.PAT}}
      - name: Test
        run: |
          ls    
          echo "$GITHUB_WORKSPACE"
      - name: Sync File 2 # 第二步，rsync推文件
        uses: Micker5502/rsync-deploy
        env:
          DEPLOY_KEY: ${{ secrets.PROJECTPW }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: "./"  # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /repo/IDS # 部署到目标文件夹
      # Runs a set of commands using the runners shell
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PROJECTPW }}
          port: 22
          script: |
            cd /repo/identityserver
            sudo docker-compose up
